export const data = [
    {id: 1, title: "What can I expect to happen during the free consultation?", description: "In our first 45-minute session, whether it's through a video call or a location we both find convenient, we'll explore your coaching goals. This is the time for you to identify what you'd like to achieve through coaching and to see if our coaching relationship feels like the right fit for you."},
    {id: 2, title: "I’m depressed. Can you help me?", description: "Many people begin coaching because they feel stuck, and that can really bring them down. I often work with people feeling blue or anxious – these are typical reactions when life doesn't go as expected. If you're dealing with ongoing sadness, a lack of interest in things that used to bring you joy, or having serious thoughts about harming yourself, it's best to seek help from a therapist or psychiatrist. As coaches, we aren't equipped to handle clinical depression or mental illnesses."},
    {id: 3, title: "How long are sessions, and what will we be covering?", description: "Each session lasts one hour, dedicated to focused exploration. Our journey kicks off with a 5 - 10 minute meditation, laying the groundwork for an optimal coaching session. Following that, we will dive into your goals, aligning them with your core values. In my role as your life coach, our approach is not just goal-oriented but mindful and embodied. Together, we'll craft a roadmap, tackle any limiting beliefs, and ensure you're progressing toward the life you desire. Expect a blend of mindfulness techniques, guided meditations, and reflective practices to make your journey both holistic and empowering."},
    {id: 4, title: "What responsibilities or commitments would I have between sessions?", description: "This journey demands active engagement. Each client is urged to invest a minimum of 10 minutes daily in meditation, complemented by guided sessions and a daily check-in via text from your coach. Furthermore, I encourage you to reflect on your daily progress and journal about any challenges you encounter. I will stand by you at every step, ensuring accountability, and together, we'll celebrate your achievements. Throughout, you'll acquire tools empowering you to coach yourself and be unstoppable."},
    {id: 5, title: "How often do we meet?", description: "We meet once a week or bi-weekly, depending on your needs and schedule, focusing on one exciting goal at a time. After the completion of a goal, you are encouraged to coach yourself using the tools acquired during our collaboration. If you need additional assistance, we can reopen the conversation."},
    {id: 6, title: "Do you accept insurance?", description: "Unfortunately, I do not accept insurance."},
    // {id: 8, title: "Lorem ipsum dolor sit amet consectetur?", description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium impedit vitae blanditiis quas iure aperiam voluptas non nam nobis, ipsa excepturi sit dolor sunt. Nemo dolorum ipsa quia optio odio."},
]


